TAMIL_NADU_CITIES = [
    ("Chennai", "Chennai"),
    ("Coimbatore", "Coimbatore"),
    ("Madurai", "Madurai"),
    ("Tiruchirappalli", "Tiruchirappalli"),
    ("Salem", "Salem"),
    ("Tirunelveli", "Tirunelveli"),
    ("Vellore", "Vellore"),
    ("Erode", "Erode"),
    ("Thoothukudi", "Thoothukudi"),
    ("Dindigul", "Dindigul"),
    ("Thanjavur", "Thanjavur"),
    ("Karur", "Karur"),
    ("Namakkal", "Namakkal"),
    ("Tiruppur", "Tiruppur"),
    ("Virudhunagar", "Virudhunagar"),
    ("Sivakasi", "Virudhunagar"),
    ("Rajapalayam", "Virudhunagar"),
    ("Tirupathur", "Vellore"),
    ("Kanchipuram", "Kanchipuram"),
    ("Cuddalore", "Cuddalore"),
    ("Nagapattinam", "Nagapattinam"),
    ("Mayiladuthurai", "Mayiladuthurai"),
    ("Kumbakonam", "Thanjavur"),
    ("Karaikudi", "Sivaganga"),
    ("Pudukkottai", "Pudukkottai"),
    ("Ramanathapuram", "Ramanathapuram"),
    ("Nagercoil", "Kanyakumari"),
    ("Kanyakumari", "Kanyakumari"),
    ("Ooty", "Nilgiris"),
    ("Hosur", "Krishnagiri"),
    ("Krishnagiri", "Krishnagiri"),
    ("Dharmapuri", "Dharmapuri"),
    ("Villupuram", "Villupuram"),
    ("Perambalur", "Perambalur"),
    ("Ariyalur", "Ariyalur"),
    ("Tiruvarur", "Tiruvarur"),
    ("Theni", "Theni"),
    ("Tenkasi", "Tenkasi"),
    ("Sivaganga", "Sivaganga"),
    ("Ranipet", "Ranipet"),
]

CHENNAI_AREAS = [
    ("Adyar", "600020"),
    ("Anna Nagar", "600040"),
    ("T. Nagar", "600017"),
    ("Nungambakkam", "600034"),
    ("Mylapore", "600004"),
    ("Velachery", "600042"),
    ("Porur", "600116"),
    ("OMR", "600097"),
    ("Guindy", "600032"),
    ("Egmore", "600008"),
    ("Chromepet", "600044"),
    ("Ambattur", "600053"),
    ("Avadi", "600054"),
    ("Tambaram", "600059"),
    ("Perambur", "600011"),
]

COIMBATORE_AREAS = [
    ("RS Puram", "641002"),
    ("Gandhipuram", "641012"),
    ("Saibaba Colony", "641011"),
    ("Peelamedu", "641004"),
    ("Singanallur", "641005"),
    ("Saravanampatti", "641035"),
    ("Vadavalli", "641041"),
    ("Ganapathy", "641006"),
]

MADURAI_AREAS = [
    ("Madurai City", "625001"),
    ("K.K. Nagar", "625020"),
    ("Anna Nagar", "625040"),
    ("Tallakulam", "625002"),
    ("Bypass Road", "625016"),
    ("Thirunagar", "625005"),
    ("Villapuram", "625012"),
]

TRICHY_AREAS = [
    ("Srirangam", "620006"),
    ("Thillai Nagar", "620018"),
    ("Cantonment", "620001"),
    ("K.K. Nagar", "620021"),
    ("Woraiyur", "620003"),
    ("Thiruverumbur", "620013"),
]

SALEM_AREAS = [
    ("Salem City", "636001"),
    ("Fairlands", "636004"),
    ("Hasthampatti", "636007"),
    ("Ammapet", "636003"),
    ("Kondalampatti", "636010"),
    ("Seelanaickenpatti", "636011"),
]
