from datetime import datetime, date, time, timedelta
import random
import json

DUMMY_USERS = [
    {
        "email": "customer1@example.com",
        "full_name": "Priya Sharma",
        "phone": "9876543210",
        "role": "customer",
        "profile_image": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200",
        "bio": "Food enthusiast from Chennai",
        "city": "Chennai",
        "area": "Anna Nagar",
    },
    {
        "email": "customer2@example.com",
        "full_name": "Karthik Rajan",
        "phone": "9876543211",
        "role": "customer",
        "profile_image": "https://images.unsplash.com/photo-1507003211169-0a9ddc96c8d6?w=200",
        "bio": "Love traditional Tamil cuisine",
        "city": "Coimbatore",
        "area": "RS Puram",
    },
    {
        "email": "customer3@example.com",
        "full_name": "Lakshmi Venkatesh",
        "phone": "9876543212",
        "role": "customer",
        "profile_image": "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200",
        "bio": "Event planner from Madurai",
        "city": "Madurai",
        "area": "K.K. Nagar",
    },
    {
        "email": "customer4@example.com",
        "full_name": "Ramesh Kumar",
        "phone": "9876543213",
        "role": "customer",
        "profile_image": "https://images.unsplash.com/photo-1500648767791-00dcc994daae?w=200",
        "bio": "Business owner, loves hosting parties",
        "city": "Chennai",
        "area": "T. Nagar",
    },
    {
        "email": "customer5@example.com",
        "full_name": "Anitha Krishnan",
        "phone": "9876543214",
        "role": "customer",
        "profile_image": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200",
        "bio": "Homemaker passionate about good food",
        "city": "Salem",
        "area": "Fairlands",
    },
    {
        "email": "chef1@example.com",
        "full_name": "Chef Rajesh Iyer",
        "phone": "9876543215",
        "role": "chef",
        "profile_image": "https://images.unsplash.com/photo-1577219491135-ce391730fb2c?w=200",
        "bio": "25 years experience in South Indian cuisine. Specialized in Chettinad and Brahmin cooking.",
        "city": "Chennai",
        "area": "Mylapore",
    },
    {
        "email": "chef2@example.com",
        "full_name": "Chef Lakshmi Narayanan",
        "phone": "9876543216",
        "role": "chef",
        "profile_image": "https://images.unsplash.com/photo-1595273670150-9c2249c6bde4?w=200",
        "bio": "Expert in traditional Tamil Brahmin cuisine. 20 years of experience.",
        "city": "Chennai",
        "area": "Adyar",
    },
    {
        "email": "chef3@example.com",
        "full_name": "Chef Anand Chettiar",
        "phone": "9876543217",
        "role": "chef",
        "profile_image": "https://images.unsplash.com/photo-1583394293214-f28184a8c95d?w=200",
        "bio": "Chettinad cuisine specialist. Known for spicy and flavorful dishes.",
        "city": "Madurai",
        "area": "Madurai City",
    },
    {
        "email": "chef4@example.com",
        "full_name": "Chef Kavitha Sundaram",
        "phone": "9876543218",
        "role": "chef",
        "profile_image": "https://images.unsplash.com/photo-1607631568010-a87245c0daf8?w=200",
        "bio": "Multi-cuisine expert. Specializes in fusion Tamil dishes.",
        "city": "Coimbatore",
        "area": "Gandhipuram",
    },
    {
        "email": "chef5@example.com",
        "full_name": "Chef Murugan Pillai",
        "phone": "9876543219",
        "role": "chef",
        "profile_image": "https://images.unsplash.com/photo-1566554273541-37a948d36877?w=200",
        "bio": "Traditional Kongu cuisine expert from Coimbatore region.",
        "city": "Coimbatore",
        "area": "Saibaba Colony",
    },
    {
        "email": "caterer1@example.com",
        "full_name": "Sri Venkateswara Caterers",
        "phone": "9876543220",
        "role": "caterer",
        "profile_image": "https://images.unsplash.com/photo-1555244162-8048e036f0b6?w=200",
        "bio": "Premium catering service for weddings and corporate events. 15 years of excellence.",
        "city": "Chennai",
        "area": "Nungambakkam",
    },
    {
        "email": "caterer2@example.com",
        "full_name": "Madurai Meenakshi Catering",
        "phone": "9876543221",
        "role": "caterer",
        "profile_image": "https://images.unsplash.com/photo-1466637574441-749b8f19452f?w=200",
        "bio": "Authentic Tamil Nadu catering. Specialists in temple weddings.",
        "city": "Madurai",
        "area": "Tallakulam",
    },
    {
        "email": "caterer3@example.com",
        "full_name": "Kongu Catering Services",
        "phone": "9876543222",
        "role": "caterer",
        "profile_image": "https://images.unsplash.com/photo-1504674900347-1c8d8e4d8a0a?w=200",
        "bio": "Traditional Kongu region catering. Best for rural weddings.",
        "city": "Coimbatore",
        "area": "Peelamedu",
    },
    {
        "email": "decorator1@example.com",
        "full_name": "Chennai Decorators",
        "phone": "9876543223",
        "role": "decorator",
        "profile_image": "https://images.unsplash.com/photo-1478146059778-26a4c17f4c2a?w=200",
        "bio": "Premium wedding and event decoration. Award-winning designs.",
        "city": "Chennai",
        "area": "Velachery",
    },
    {
        "email": "decorator2@example.com",
        "full_name": "Madurai Floral Decor",
        "phone": "9876543224",
        "role": "decorator",
        "profile_image": "https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=200",
        "bio": "Traditional Tamil wedding decorations with fresh flowers.",
        "city": "Madurai",
        "area": "Anna Nagar",
    },
    {
        "email": "admin@example.com",
        "full_name": "Admin User",
        "phone": "9876543225",
        "role": "admin",
        "profile_image": "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200",
        "bio": "System Administrator",
        "city": "Chennai",
        "area": "Nungambakkam",
    },
]

CHEF_SERVICES = [
    {
        "user_email": "chef1@example.com",
        "title": "Authentic Chettinad & Brahmin Cuisine",
        "description": "Experience the rich flavors of Chettinad and traditional Brahmin cooking. I bring 25 years of expertise to your kitchen, creating memorable dishes for your special occasions.",
        "service_type": "chef",
        "cuisine_types": ["Chettinad", "Brahmin", "South Indian"],
        "event_types": ["Wedding", "Housewarming", "Birthday", "Corporate"],
        "experience_years": 25,
        "price_per_event": 15000,
        "serves_veg": True,
        "serves_non_veg": True,
        "min_guests": 20,
        "max_guests": 300,
        "images": [
            "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400",
            "https://images.unsplash.com/photo-1567337710282-1c8079d9cb7d?w=400",
        ],
        "dishes": [
            {
                "name": "Chettinad Chicken Curry",
                "description": "Signature spicy chicken curry with aromatic Chettinad masala",
                "image_url": "https://images.unsplash.com/photo-1565559753640-6ecc3e7a6c20?w=300",
                "cuisine_type": "Chettinad",
                "is_veg": False,
            },
            {
                "name": "Brahmin Sambar",
                "description": "Traditional Brahmin-style sambar with fresh vegetables",
                "image_url": "https://images.unsplash.com/photo-1546833999-b9f5812f9c53?w=300",
                "cuisine_type": "Brahmin",
                "is_veg": True,
            },
            {
                "name": "Mutton Biryani",
                "description": "Aromatic Chettinad-style mutton biryani",
                "image_url": "https://images.unsplash.com/photo-1563379092698-ea7c5c0a4d2d?w=300",
                "cuisine_type": "Chettinad",
                "is_veg": False,
            },
        ],
    },
    {
        "user_email": "chef2@example.com",
        "title": "Traditional Tamil Brahmin Cooking",
        "description": "Pure vegetarian Brahmin cuisine prepared with authentic recipes passed down through generations. Perfect for religious ceremonies and family gatherings.",
        "service_type": "chef",
        "cuisine_types": ["Brahmin", "Iyer", "Iyengar", "South Indian"],
        "event_types": ["Wedding", "Upanayanam", "Sashtiapthapoorthi", "Housewarming"],
        "experience_years": 20,
        "price_per_event": 12000,
        "serves_veg": True,
        "serves_non_veg": False,
        "min_guests": 25,
        "max_guests": 500,
        "images": [
            "https://images.unsplash.com/photo-1631452180519-8e7357e5d7e8?w=400",
            "https://images.unsplash.com/photo-1567337710282-1c8079d9cb7d?w=400",
        ],
        "dishes": [
            {
                "name": "Paruppu Urundai Kuzhambu",
                "description": "Lentil balls in tangy tamarind gravy",
                "image_url": "https://images.unsplash.com/photo-1546833999-b9f5812f9c53?w=300",
                "cuisine_type": "Brahmin",
                "is_veg": True,
            },
            {
                "name": "Rasam",
                "description": "Traditional pepper-rasam with medicinal properties",
                "image_url": "https://images.unsplash.com/photo-1545248218-20c1b4c6d6c0?w=300",
                "cuisine_type": "Brahmin",
                "is_veg": True,
            },
            {
                "name": "Thayir Sadam",
                "description": "Creamy curd rice with tempered spices",
                "image_url": "https://images.unsplash.com/photo-1596797038530-2e107299f775?w=300",
                "cuisine_type": "Brahmin",
                "is_veg": True,
            },
        ],
    },
    {
        "user_email": "chef3@example.com",
        "title": "Royal Chettinad Feast",
        "description": "Experience the royal flavors of Chettinad cuisine. Known for bold spices and unique cooking techniques from the Chettiar community.",
        "service_type": "chef",
        "cuisine_types": ["Chettinad", "South Indian", "Non-Veg"],
        "event_types": ["Wedding", "Birthday", "Corporate", "Family Gathering"],
        "experience_years": 18,
        "price_per_event": 18000,
        "serves_veg": True,
        "serves_non_veg": True,
        "min_guests": 30,
        "max_guests": 400,
        "images": [
            "https://images.unsplash.com/photo-1567337710282-1c8079d9cb7d?w=400",
            "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400",
        ],
        "dishes": [
            {
                "name": "Chettinad Pepper Chicken",
                "description": "Fiery pepper chicken with Chettinad spices",
                "image_url": "https://images.unsplash.com/photo-1565559753640-6ecc3e7a6c20?w=300",
                "cuisine_type": "Chettinad",
                "is_veg": False,
            },
            {
                "name": "Kara Kuzhambu",
                "description": "Spicy tamarind-based curry",
                "image_url": "https://images.unsplash.com/photo-1546833999-b9f5812f9c53?w=300",
                "cuisine_type": "Chettinad",
                "is_veg": True,
            },
            {
                "name": "Fish Fry",
                "description": "Crispy Chettinad-style fish fry",
                "image_url": "https://images.unsplash.com/photo-1580476262798-b3cf4e7c8d4e?w=300",
                "cuisine_type": "Chettinad",
                "is_veg": False,
            },
        ],
    },
    {
        "user_email": "chef4@example.com",
        "title": "Fusion Tamil Cuisine",
        "description": "Modern fusion dishes combining traditional Tamil flavors with contemporary techniques. Perfect for modern weddings and corporate events.",
        "service_type": "chef",
        "cuisine_types": ["Fusion", "South Indian", "Continental"],
        "event_types": ["Wedding", "Corporate", "Birthday", "Anniversary"],
        "experience_years": 12,
        "price_per_event": 20000,
        "serves_veg": True,
        "serves_non_veg": True,
        "min_guests": 50,
        "max_guests": 500,
        "images": [
            "https://images.unsplash.com/photo-1504674900347-1c8d8e4d8a0a?w=400",
            "https://images.unsplash.com/photo-1466637574441-749b8f19452f?w=400",
        ],
        "dishes": [
            {
                "name": "Quinoa Pongal",
                "description": "Healthy twist on traditional ven pongal",
                "image_url": "https://images.unsplash.com/photo-1596797038530-2e107299f775?w=300",
                "cuisine_type": "Fusion",
                "is_veg": True,
            },
            {
                "name": "Chettinad Pasta",
                "description": "Italian pasta with Chettinad spice blend",
                "image_url": "https://images.unsplash.com/photo-1563399935488-3d8e4c2e9c5e?w=300",
                "cuisine_type": "Fusion",
                "is_veg": True,
            },
            {
                "name": "Masala Risotto",
                "description": "Creamy risotto with Indian spices",
                "image_url": "https://images.unsplash.com/photo-1476124289251-359d5e3f8a3c?w=300",
                "cuisine_type": "Fusion",
                "is_veg": True,
            },
        ],
    },
    {
        "user_email": "chef5@example.com",
        "title": "Kongu Nadu Traditional Cooking",
        "description": "Authentic Kongu region cuisine from Coimbatore. Known for unique recipes and rustic flavors from the Kongu community.",
        "service_type": "chef",
        "cuisine_types": ["Kongu", "South Indian", "Traditional"],
        "event_types": ["Wedding", "Housewarming", "Family Function"],
        "experience_years": 22,
        "price_per_event": 14000,
        "serves_veg": True,
        "serves_non_veg": True,
        "min_guests": 25,
        "max_guests": 350,
        "images": [
            "https://images.unsplash.com/photo-1567337710282-1c8079d9cb7d?w=400",
            "https://images.unsplash.com/photo-1631452180519-8e7357e5d7e8?w=400",
        ],
        "dishes": [
            {
                "name": "Kongu Chicken Curry",
                "description": "Rustic chicken curry with Kongu spices",
                "image_url": "https://images.unsplash.com/photo-1565559753640-6ecc3e7a6c20?w=300",
                "cuisine_type": "Kongu",
                "is_veg": False,
            },
            {
                "name": "Arachuvitta Sambar",
                "description": "Sambar with freshly ground masala",
                "image_url": "https://images.unsplash.com/photo-1546833999-b9f5812f9c53?w=300",
                "cuisine_type": "Kongu",
                "is_veg": True,
            },
            {
                "name": "Kongu Biryani",
                "description": "Unique Kongu-style biryani",
                "image_url": "https://images.unsplash.com/photo-1563379092698-ea7c5c0a4d2d?w=300",
                "cuisine_type": "Kongu",
                "is_veg": False,
            },
        ],
    },
]

EVENT_HISTORY_DATA = [
    {
        "service_index": 0,
        "event_date": "2024-01-15",
        "event_type": "Wedding",
        "number_of_guests": 250,
        "venue": "Chennai Trade Centre, Nandambakkam",
        "cuisine_types": ["Chettinad", "Brahmin"],
        "customer_name": "Suresh & Priya",
        "customer_testimonial": "The food was absolutely divine! Chef Rajesh made our wedding unforgettable.",
        "is_featured": True,
        "photos": [
            "https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=400",
            "https://images.unsplash.com/photo-1478146059778-26a4c17f4c2a?w=400",
        ],
    },
    {
        "service_index": 0,
        "event_date": "2024-02-20",
        "event_type": "Housewarming",
        "number_of_guests": 80,
        "venue": "Anna Nagar, Chennai",
        "cuisine_types": ["Brahmin"],
        "customer_name": "Raman Family",
        "customer_testimonial": "Traditional Brahmin food just like grandma used to make!",
        "is_featured": True,
        "photos": [
            "https://images.unsplash.com/photo-1466637574441-749b8f19452f?w=400",
        ],
    },
    {
        "service_index": 0,
        "event_date": "2024-03-10",
        "event_type": "Corporate Event",
        "number_of_guests": 150,
        "venue": "IT Park, OMR Chennai",
        "cuisine_types": ["Chettinad", "South Indian"],
        "customer_name": "Tech Solutions Pvt Ltd",
        "customer_testimonial": "Excellent catering for our annual day celebration.",
        "is_featured": True,
        "photos": [
            "https://images.unsplash.com/photo-1504674900347-1c8d8e4d8a0a?w=400",
        ],
    },
    {
        "service_index": 0,
        "event_date": "2023-12-05",
        "event_type": "Birthday",
        "number_of_guests": 50,
        "venue": "T. Nagar, Chennai",
        "cuisine_types": ["Chettinad"],
        "customer_name": "Kumar Family",
        "customer_testimonial": "The biryani was the star of the party!",
        "is_featured": False,
        "photos": [],
    },
    {
        "service_index": 0,
        "event_date": "2023-11-20",
        "event_type": "Wedding",
        "number_of_guests": 300,
        "venue": "Mahabalipuram",
        "cuisine_types": ["Chettinad", "Brahmin"],
        "customer_name": "Venkat & Lakshmi",
        "customer_testimonial": "Best decision we made for our beach wedding!",
        "is_featured": True,
        "photos": [
            "https://images.unsplash.com/photo-1519741497674-611481863552?w=400",
        ],
    },
    {
        "service_index": 1,
        "event_date": "2024-01-25",
        "event_type": "Upanayanam",
        "number_of_guests": 200,
        "venue": "Mylapore, Chennai",
        "cuisine_types": ["Brahmin", "Iyer"],
        "customer_name": "Sharma Family",
        "customer_testimonial": "Authentic Iyer cuisine for our son's sacred thread ceremony.",
        "is_featured": True,
        "photos": [
            "https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=400",
        ],
    },
    {
        "service_index": 1,
        "event_date": "2024-02-10",
        "event_type": "Sashtiapthapoorthi",
        "number_of_guests": 300,
        "venue": "Kanchipuram",
        "cuisine_types": ["Brahmin"],
        "customer_name": "Krishnamurthy Family",
        "customer_testimonial": "Perfect traditional feast for our 60th birthday celebration.",
        "is_featured": True,
        "photos": [
            "https://images.unsplash.com/photo-1478146059778-26a4c17f4c2a?w=400",
        ],
    },
    {
        "service_index": 1,
        "event_date": "2023-12-15",
        "event_type": "Wedding",
        "number_of_guests": 400,
        "venue": "Chennai",
        "cuisine_types": ["Brahmin", "Iyengar"],
        "customer_name": "Srinivasan & Padma",
        "customer_testimonial": "Pure vegetarian feast that impressed all our guests.",
        "is_featured": True,
        "photos": [
            "https://images.unsplash.com/photo-1519741497674-611481863552?w=400",
        ],
    },
    {
        "service_index": 1,
        "event_date": "2023-11-05",
        "event_type": "Housewarming",
        "number_of_guests": 100,
        "venue": "Adyar, Chennai",
        "cuisine_types": ["Brahmin"],
        "customer_name": "Venkatesh Family",
        "customer_testimonial": "Delicious traditional food for our grihapravesam.",
        "is_featured": False,
        "photos": [],
    },
    {
        "service_index": 1,
        "event_date": "2023-10-20",
        "event_type": "Wedding",
        "number_of_guests": 350,
        "venue": "Tirupati",
        "cuisine_types": ["Brahmin"],
        "customer_name": "Raghavan & Sita",
        "customer_testimonial": "The most authentic Brahmin wedding feast!",
        "is_featured": True,
        "photos": [
            "https://images.unsplash.com/photo-1466637574441-749b8f19452f?w=400",
        ],
    },
    {
        "service_index": 2,
        "event_date": "2024-01-20",
        "event_type": "Wedding",
        "number_of_guests": 400,
        "venue": "Madurai",
        "cuisine_types": ["Chettinad"],
        "customer_name": "Pandian & Thangam",
        "customer_testimonial": "Royal Chettinad feast for our royal wedding!",
        "is_featured": True,
        "photos": [
            "https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=400",
        ],
    },
    {
        "service_index": 2,
        "event_date": "2024-02-15",
        "event_type": "Corporate Event",
        "number_of_guests": 200,
        "venue": "Madurai IT Park",
        "cuisine_types": ["Chettinad", "South Indian"],
        "customer_name": "Madurai Tech Park",
        "customer_testimonial": "Spicy and flavorful - everyone loved it!",
        "is_featured": True,
        "photos": [
            "https://images.unsplash.com/photo-1504674900347-1c8d8e4d8a0a?w=400",
        ],
    },
    {
        "service_index": 2,
        "event_date": "2023-12-10",
        "event_type": "Birthday",
        "number_of_guests": 75,
        "venue": "K.K. Nagar, Madurai",
        "cuisine_types": ["Chettinad"],
        "customer_name": "Chinnasamy Family",
        "customer_testimonial": "The pepper chicken was out of this world!",
        "is_featured": False,
        "photos": [],
    },
    {
        "service_index": 2,
        "event_date": "2023-11-15",
        "event_type": "Wedding",
        "number_of_guests": 500,
        "venue": "Karaikudi",
        "cuisine_types": ["Chettinad"],
        "customer_name": "Chettiar Family",
        "customer_testimonial": "Authentic Chettinad cuisine in the heart of Chettinad!",
        "is_featured": True,
        "photos": [
            "https://images.unsplash.com/photo-1519741497674-611481863552?w=400",
        ],
    },
    {
        "service_index": 2,
        "event_date": "2023-10-25",
        "event_type": "Family Gathering",
        "number_of_guests": 100,
        "venue": "Ramanathapuram",
        "cuisine_types": ["Chettinad"],
        "customer_name": "Ramar Family",
        "customer_testimonial": "Best family reunion food ever!",
        "is_featured": True,
        "photos": [
            "https://images.unsplash.com/photo-1478146059778-26a4c17f4c2a?w=400",
        ],
    },
    {
        "service_index": 3,
        "event_date": "2024-02-25",
        "event_type": "Corporate Event",
        "number_of_guests": 300,
        "venue": "Codissia, Coimbatore",
        "cuisine_types": ["Fusion", "South Indian"],
        "customer_name": "Coimbatore Industries",
        "customer_testimonial": "Modern twist on traditional food - loved by all!",
        "is_featured": True,
        "photos": [
            "https://images.unsplash.com/photo-1504674900347-1c8d8e4d8a0a?w=400",
        ],
    },
    {
        "service_index": 3,
        "event_date": "2024-01-30",
        "event_type": "Wedding",
        "number_of_guests": 350,
        "venue": "Coimbatore Club",
        "cuisine_types": ["Fusion", "Continental"],
        "customer_name": "Karthik & Divya",
        "customer_testimonial": "Perfect blend of tradition and modernity!",
        "is_featured": True,
        "photos": [
            "https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=400",
        ],
    },
    {
        "service_index": 3,
        "event_date": "2023-12-20",
        "event_type": "Anniversary",
        "number_of_guests": 100,
        "venue": "RS Puram, Coimbatore",
        "cuisine_types": ["Fusion"],
        "customer_name": "Sundaram Family",
        "customer_testimonial": "Unique fusion dishes made our anniversary special!",
        "is_featured": False,
        "photos": [],
    },
    {
        "service_index": 3,
        "event_date": "2023-11-10",
        "event_type": "Birthday",
        "number_of_guests": 80,
        "venue": "Gandhipuram, Coimbatore",
        "cuisine_types": ["Fusion", "South Indian"],
        "customer_name": "Prasad Family",
        "customer_testimonial": "Kids and adults both loved the fusion menu!",
        "is_featured": True,
        "photos": [
            "https://images.unsplash.com/photo-1478146059778-26a4c17f4c2a?w=400",
        ],
    },
    {
        "service_index": 3,
        "event_date": "2023-10-15",
        "event_type": "Corporate Event",
        "number_of_guests": 200,
        "venue": "Tidel Park, Coimbatore",
        "cuisine_types": ["Fusion"],
        "customer_name": "Software Solutions",
        "customer_testimonial": "Impressed our international clients!",
        "is_featured": True,
        "photos": [
            "https://images.unsplash.com/photo-1466637574441-749b8f19452f?w=400",
        ],
    },
    {
        "service_index": 4,
        "event_date": "2024-01-10",
        "event_type": "Wedding",
        "number_of_guests": 300,
        "venue": "Pollachi",
        "cuisine_types": ["Kongu", "Traditional"],
        "customer_name": "Gounder Family",
        "customer_testimonial": "Authentic Kongu cuisine for our traditional wedding!",
        "is_featured": True,
        "photos": [
            "https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=400",
        ],
    },
    {
        "service_index": 4,
        "event_date": "2024-02-05",
        "event_type": "Housewarming",
        "number_of_guests": 150,
        "venue": "Saibaba Colony, Coimbatore",
        "cuisine_types": ["Kongu"],
        "customer_name": "Muthusamy Family",
        "customer_testimonial": "Traditional Kongu feast for our new home!",
        "is_featured": True,
        "photos": [
            "https://images.unsplash.com/photo-1478146059778-26a4c17f4c2a?w=400",
        ],
    },
    {
        "service_index": 4,
        "event_date": "2023-12-25",
        "event_type": "Family Function",
        "number_of_guests": 100,
        "venue": "Tiruppur",
        "cuisine_types": ["Kongu", "Traditional"],
        "customer_name": "Nadar Family",
        "customer_testimonial": "Rustic flavors that reminded us of our roots!",
        "is_featured": False,
        "photos": [],
    },
    {
        "service_index": 4,
        "event_date": "2023-11-20",
        "event_type": "Wedding",
        "number_of_guests": 400,
        "venue": "Erode",
        "cuisine_types": ["Kongu"],
        "customer_name": "Kongu Family",
        "customer_testimonial": "Best Kongu biryani we've ever had!",
        "is_featured": True,
        "photos": [
            "https://images.unsplash.com/photo-1519741497674-611481863552?w=400",
        ],
    },
    {
        "service_index": 4,
        "event_date": "2023-10-30",
        "event_type": "Housewarming",
        "number_of_guests": 80,
        "venue": "Peelamedu, Coimbatore",
        "cuisine_types": ["Kongu"],
        "customer_name": "Ramasamy Family",
        "customer_testimonial": "Perfect traditional food for our grihapravesam!",
        "is_featured": True,
        "photos": [
            "https://images.unsplash.com/photo-1504674900347-1c8d8e4d8a0a?w=400",
        ],
    },
]

SAMPLE_BOOKINGS = [
    {
        "customer_email": "customer1@example.com",
        "service_index": 0,
        "event_date": "2024-04-15",
        "event_time": "19:00",
        "event_type": "Wedding",
        "event_address": "Chennai Trade Centre, Nandambakkam",
        "city": "Chennai",
        "area": "Nungambakkam",
        "number_of_guests": 200,
        "special_requirements": "Need pure veg options for some guests",
        "base_amount": 15000,
        "total_amount": 18000,
        "status": "confirmed",
    },
    {
        "customer_email": "customer2@example.com",
        "service_index": 1,
        "event_date": "2024-04-20",
        "event_time": "10:00",
        "event_type": "Upanayanam",
        "event_address": "Kanchipuram Temple Hall",
        "city": "Chennai",
        "area": "Adyar",
        "number_of_guests": 150,
        "special_requirements": "Traditional Brahmin menu required",
        "base_amount": 12000,
        "total_amount": 15000,
        "status": "confirmed",
    },
    {
        "customer_email": "customer3@example.com",
        "service_index": 2,
        "event_date": "2024-05-01",
        "event_time": "12:00",
        "event_type": "Wedding",
        "event_address": "Madurai Wedding Hall",
        "city": "Madurai",
        "area": "Madurai City",
        "number_of_guests": 300,
        "special_requirements": "Non-veg Chettinad menu",
        "base_amount": 18000,
        "total_amount": 22000,
        "status": "pending",
    },
    {
        "customer_email": "customer4@example.com",
        "service_index": 3,
        "event_date": "2024-05-10",
        "event_time": "19:30",
        "event_type": "Corporate Event",
        "event_address": "IT Park, OMR",
        "city": "Chennai",
        "area": "OMR",
        "number_of_guests": 250,
        "special_requirements": "Fusion menu with both veg and non-veg",
        "base_amount": 20000,
        "total_amount": 25000,
        "status": "confirmed",
    },
    {
        "customer_email": "customer5@example.com",
        "service_index": 4,
        "event_date": "2024-05-15",
        "event_time": "11:00",
        "event_type": "Housewarming",
        "event_address": "Saibaba Colony, Coimbatore",
        "city": "Coimbatore",
        "area": "Saibaba Colony",
        "number_of_guests": 100,
        "special_requirements": "Traditional Kongu menu",
        "base_amount": 14000,
        "total_amount": 16000,
        "status": "pending",
    },
    {
        "customer_email": "customer1@example.com",
        "service_index": 2,
        "event_date": "2024-03-10",
        "event_time": "19:00",
        "event_type": "Birthday",
        "event_address": "Anna Nagar, Chennai",
        "city": "Chennai",
        "area": "Anna Nagar",
        "number_of_guests": 75,
        "special_requirements": "Spicy Chettinad food",
        "base_amount": 18000,
        "total_amount": 20000,
        "status": "completed",
    },
    {
        "customer_email": "customer2@example.com",
        "service_index": 0,
        "event_date": "2024-03-15",
        "event_time": "12:00",
        "event_type": "Housewarming",
        "event_address": "RS Puram, Coimbatore",
        "city": "Coimbatore",
        "area": "RS Puram",
        "number_of_guests": 80,
        "special_requirements": "Mix of veg and non-veg",
        "base_amount": 15000,
        "total_amount": 17000,
        "status": "completed",
    },
    {
        "customer_email": "customer3@example.com",
        "service_index": 1,
        "event_date": "2024-03-20",
        "event_time": "10:00",
        "event_type": "Wedding",
        "event_address": "Mylapore, Chennai",
        "city": "Chennai",
        "area": "Mylapore",
        "number_of_guests": 400,
        "special_requirements": "Pure veg Brahmin menu",
        "base_amount": 12000,
        "total_amount": 18000,
        "status": "completed",
    },
    {
        "customer_email": "customer4@example.com",
        "service_index": 3,
        "event_date": "2024-03-25",
        "event_time": "19:00",
        "event_type": "Anniversary",
        "event_address": "T. Nagar, Chennai",
        "city": "Chennai",
        "area": "T. Nagar",
        "number_of_guests": 100,
        "special_requirements": "Fusion menu with wine pairing suggestions",
        "base_amount": 20000,
        "total_amount": 23000,
        "status": "completed",
    },
    {
        "customer_email": "customer5@example.com",
        "service_index": 4,
        "event_date": "2024-03-30",
        "event_time": "11:00",
        "event_type": "Family Function",
        "event_address": "Fairlands, Salem",
        "city": "Salem",
        "area": "Fairlands",
        "number_of_guests": 120,
        "special_requirements": "Traditional Kongu feast",
        "base_amount": 14000,
        "total_amount": 16000,
        "status": "completed",
    },
]

SAMPLE_REVIEWS = [
    {
        "booking_index": 5,
        "rating": 5,
        "comment": "Chef Anand made my birthday unforgettable! The Chettinad chicken was absolutely divine. Every dish was perfectly spiced and flavorful. Highly recommend!",
    },
    {
        "booking_index": 6,
        "rating": 5,
        "comment": "Chef Rajesh exceeded all expectations for our housewarming. The mix of Chettinad and Brahmin dishes was perfect. Guests are still talking about the food!",
    },
    {
        "booking_index": 7,
        "rating": 4,
        "comment": "Authentic Brahmin cuisine for our wedding. Chef Lakshmi's attention to tradition was remarkable. Only wish there were more dessert options.",
    },
    {
        "booking_index": 8,
        "rating": 5,
        "comment": "The fusion menu was a hit! Chef Kavitha's innovative dishes impressed everyone. The Chettinad pasta was unique and delicious!",
    },
    {
        "booking_index": 9,
        "rating": 4,
        "comment": "Traditional Kongu food at its best! Chef Murugan brought the authentic taste of Kongu Nadu to our function. Will definitely book again.",
    },
]

CATERER_SERVICES = [
    {
        "user_email": "caterer1@example.com",
        "title": "Sri Venkateswara Premium Catering",
        "description": "Premium catering service for weddings and corporate events. We specialize in both traditional Tamil cuisine and modern fusion menus. Our team of 50+ staff ensures flawless execution for events of any size.",
        "service_type": "caterer",
        "cuisine_types": ["South Indian", "North Indian", "Chinese", "Continental"],
        "event_types": [
            "Wedding",
            "Corporate",
            "Birthday",
            "Anniversary",
            "Conference",
        ],
        "experience_years": 15,
        "price_per_event": 50000,
        "serves_veg": True,
        "serves_non_veg": True,
        "min_guests": 100,
        "max_guests": 2000,
        "images": [
            "https://images.unsplash.com/photo-1555244162-8048e036f0b6?w=400",
            "https://images.unsplash.com/photo-1466637574441-749b8f19452f?w=400",
        ],
    },
    {
        "user_email": "caterer2@example.com",
        "title": "Madurai Meenakshi Traditional Catering",
        "description": "Authentic Tamil Nadu catering with a focus on temple weddings and religious ceremonies. We follow traditional recipes passed down through generations. Pure vegetarian catering with Brahmin-style cooking.",
        "service_type": "caterer",
        "cuisine_types": ["Brahmin", "Iyer", "Iyengar", "Traditional Tamil"],
        "event_types": [
            "Wedding",
            "Upanayanam",
            "Sashtiapthapoorthi",
            "Temple Function",
        ],
        "experience_years": 25,
        "price_per_event": 35000,
        "serves_veg": True,
        "serves_non_veg": False,
        "min_guests": 50,
        "max_guests": 1500,
        "images": [
            "https://images.unsplash.com/photo-1466637574441-749b8f19452f?w=400",
            "https://images.unsplash.com/photo-1504674900347-1c8d8e4d8a0a?w=400",
        ],
    },
    {
        "user_email": "caterer3@example.com",
        "title": "Kongu Nadu Catering Services",
        "description": "Traditional Kongu region catering from Coimbatore. We bring the rustic flavors of Kongu Nadu to your events. Specializing in rural weddings and family functions with authentic local recipes.",
        "service_type": "caterer",
        "cuisine_types": ["Kongu", "Traditional", "Rural Tamil"],
        "event_types": ["Wedding", "Housewarming", "Family Function", "Village Event"],
        "experience_years": 20,
        "price_per_event": 30000,
        "serves_veg": True,
        "serves_non_veg": True,
        "min_guests": 75,
        "max_guests": 1000,
        "images": [
            "https://images.unsplash.com/photo-1504674900347-1c8d8e4d8a0a?w=400",
            "https://images.unsplash.com/photo-1466637574441-749b8f19452f?w=400",
        ],
    },
]

DECORATOR_SERVICES = [
    {
        "user_email": "decorator1@example.com",
        "title": "Chennai Premium Decorators",
        "description": "Award-winning wedding and event decoration services. We create stunning designs for weddings, corporate events, and special occasions. Our team specializes in both traditional Tamil and modern contemporary styles.",
        "service_type": "decorator",
        "cuisine_types": ["Traditional", "Modern", "Floral", "Theme-based"],
        "event_types": [
            "Wedding",
            "Corporate",
            "Birthday",
            "Anniversary",
            "Stage Show",
        ],
        "experience_years": 12,
        "price_per_event": 75000,
        "serves_veg": True,
        "serves_non_veg": True,
        "min_guests": 50,
        "max_guests": 2000,
        "images": [
            "https://images.unsplash.com/photo-1478146059778-26a4c17f4c2a?w=400",
            "https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=400",
        ],
    },
    {
        "user_email": "decorator2@example.com",
        "title": "Madurai Floral Decorators",
        "description": "Traditional Tamil wedding decorations using fresh flowers. We specialize in mandapam decoration, stage setup, and floral arrangements. Our designs reflect the rich cultural heritage of Tamil Nadu.",
        "service_type": "decorator",
        "cuisine_types": ["Traditional", "Floral", "Mandapam", "Temple Style"],
        "event_types": [
            "Wedding",
            "Temple Function",
            "Housewarming",
            "Religious Ceremony",
        ],
        "experience_years": 18,
        "price_per_event": 50000,
        "serves_veg": True,
        "serves_non_veg": False,
        "min_guests": 30,
        "max_guests": 1000,
        "images": [
            "https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=400",
            "https://images.unsplash.com/photo-1478146059778-26a4c17f4c2a?w=400",
        ],
    },
]

AVAILABILITY_DATA = []

today = date.today()
for service_idx in range(10):
    for day_offset in range(30):
        slot_date = today + timedelta(days=day_offset)
        for start_hour in [9, 12, 15, 18]:
            AVAILABILITY_DATA.append(
                {
                    "service_index": service_idx,
                    "date": slot_date.isoformat(),
                    "start_time": f"{start_hour:02d}:00",
                    "end_time": f"{start_hour + 3:02d}:00",
                    "is_available": True,
                }
            )
